device: cuda
checkpoint_dir: "checkpoints"
use_mmap: True
batch_size: 32
batch_num: 256
context_length: 32
resume_from: False
checkpoint_iter: 64
model:
  vocab_size: 10000
  context_len: 32
  d_model: 256
  num_layers: 1
  num_heads: 2
  d_ff: null
  rope_theta: 10000.0
optim:
  lr: 1.0e-3
  betas: [0.9, 0.999]
  eps: 1.0e-8
  weight_decay: 0.01
dataset:
  train: '/home/wuhang/projects/stanford-cs336-assignment1/data/tinystories_sample.npy'
  val: '/home/wuhang/projects/stanford-cs336-assignment1/data/tinystories_sample.npy'